name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: index.html.gz
          path: index.html.gz
          if-no-files-found: error
          retention-days: 30
