name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Web UI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm i
      
      - name: Build Web UI (All)
        run: |-
          npm run build:all
          mv index.html.gz LANG_ALL_index.html.gz
      
      - name: Upload Web UI (All) to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ESP3D-WEBUI_LANG_ALL
          path: LANG_ALL_index.html.gz
          if-no-files-found: error
          retention-days: 30

      - name: Build Web UI (English)
        run: |-
          npm run build:en
          mv index.html.gz LANG_EN_index.html.gz
      
      - name: Upload Web UI (all languages) to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ESP3D-WEBUI_LANG_ALL
          path: LANG_EN_index.html.gz
          if-no-files-found: error
          retention-days: 30
